#!/usr/bin/env python3
import sys
from pathlib import Path


def format_summary(title, content_map):
    """
    Formatea un resumen tecnico de manera estandarizada.
    """
    summary = f"# Technical Summary: {title}\n\n"

    sections = {
        "problem": "## Problem Statement",
        "methodology": "## Methodology",
        "findings": "## Key Findings",
        "limitations": "## Limitations",
        "conclusion": "## Conclusion",
    }

    for key, header in sections.items():
        val = content_map.get(key, "No especificado.")
        summary += f"{header}\n{val}\n\n"

    summary += "---\n*Generated by @paper-summarizer*"
    return summary


if __name__ == "__main__":
    # Este script puede ser extendido para interactuar con APIs de OCR o parsing de PDF.
    # Por ahora sirve como formateador de salida para la IA.
    if len(sys.argv) < 2:
        print("Uso: python summarize.py [title]")
    else:
        print(f"Skill @paper-summarizer ready for {sys.argv[1]}")
